In [2]:
from google.colab import files
uploaded = files.upload()

Saving UNSW_NB15_training-set.parquet to UNSW_NB15_training-set (1).parquet

In [10]:
import pandas as pd

df = pd.read_parquet("UNSW_NB15_training-set.parquet")

print(df.shape)
print(df.head())
print(df.info())

(175341, 36)
        dur proto service state  spkts  dpkts  sbytes  dbytes       rate  \
0  0.121478   tcp       -   FIN      6      4     258     172  74.087486
1  0.649902   tcp       -   FIN     14     38     734   42014  78.473373
2  1.623129   tcp       -   FIN      8     16     364   13186  14.170161
3  1.681642   tcp     ftp   FIN     12     12     628     770  13.677108
4  0.449454   tcp       -   FIN     10      6     534     268  33.373825

          sload  ...  trans_depth  response_body_len  ct_src_dport_ltm  \
0  14158.942383  ...            0                  0                 1
1   8395.112305  ...            0                  0                 1
2   1572.271851  ...            0                  0                 1
3   2740.178955  ...            0                  0                 1
4   8561.499023  ...            0                  0                 2

   ct_dst_sport_ltm  is_ftp_login  ct_ftp_cmd  ct_flw_http_mthd  \
0                 1             0           0                 0
1                 1             0           0                 0
2                 1             0           0                 0
3                 1             1           1                 0
4                 1             0           0                 0

   is_sm_ips_ports  attack_cat  label
0                0      Normal      0
1                0      Normal      0
2                0      Normal      0
3                0      Normal      0
4                0      Normal      0

[5 rows x 36 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175341 entries, 0 to 175340
Data columns (total 36 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   dur                175341 non-null  float32
 1   proto              175341 non-null  category
 2   service            175341 non-null  category
 3   state              175341 non-null  category
 4   spkts              175341 non-null  int16
 5   dpkts              175341 non-null  int16
 6   sbytes             175341 non-null  int32
 7   dbytes             175341 non-null  int32
 8   rate               175341 non-null  float32
 9   sload              175341 non-null  float32
 10  dload              175341 non-null  float32
 11  sloss              175341 non-null  int16
 12  dloss              175341 non-null  int16
 13  sinpkt             175341 non-null  float32
 14  dinpkt             175341 non-null  float32
 15  sjit               175341 non-null  float32
 16  djit               175341 non-null  float32
 17  swin               175341 non-null  int16
 18  stcpb              175341 non-null  int64
 19  dtcpb              175341 non-null  int64
 20  dwin               175341 non-null  int16
 21  tcprtt             175341 non-null  float32
 22  synack             175341 non-null  float32
 23  ackdat             175341 non-null  float32
 24  smean              175341 non-null  int16
 25  dmean              175341 non-null  int16
 26  trans_depth        175341 non-null  int16
 27  response_body_len  175341 non-null  int32
 28  ct_src_dport_ltm   175341 non-null  int8
 29  ct_dst_sport_ltm   175341 non-null  int8
 30  is_ftp_login       175341 non-null  int8
 31  ct_ftp_cmd         175341 non-null  int8
 32  ct_flw_http_mthd   175341 non-null  int8
 33  is_sm_ips_ports    175341 non-null  int8
 34  attack_cat         175341 non-null  category
 35  label              175341 non-null  int8
dtypes: category(4), float32(11), int16(9), int32(3), int64(2), int8(7)
memory usage: 17.1 MB
None

In [11]:
df['attack_cat'].value_counts()

attack_cat
Normal            56000
Generic           40000
Exploits          33393
Fuzzers           18184
DoS               12264
Reconnaissance    10491
Analysis           2000
Backdoor           1746
Shellcode          1133
Worms               130
Name: count, dtype: int64

In [12]:
df['label'].value_counts()

label
1    119341
0     56000
Name: count, dtype: int64

In [13]:
df.describe()

,dur,spkts,dpkts,sbytes,dbytes,rate,sload,dload,sloss,dloss,...,dmean,trans_depth,response_body_len,ct_src_dport_ltm,ct_dst_sport_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,is_sm_ips_ports,label
count,175341.000000,175341.000000,175341.000000,1.753410e+05,1.753410e+05,175341.000000,1.753410e+05,1.753410e+05,175341.000000,175341.000000,...,175341.000000,175341.000000,1.753410e+05,175341.000000,175341.000000,175341.000000,175341.000000,175341.000000,175341.000000,175341.000000
mean,1.359389,20.298664,18.969591,8.844844e+03,1.492892e+04,95406.179688,7.345403e+07,6.712055e+05,4.953000,6.948010,...,124.173382,0.105982,2.144292e+03,5.383538,4.206255,0.014948,0.014948,0.133066,0.015752,0.680622
std,6.483313,136.887597,110.258271,1.747656e+05,1.436542e+05,165417.671875,1.883701e+08,2.423637e+06,66.005059,52.732999,...,258.317056,0.776911,5.420797e+04,8.047104,5.783585,0.126048,0.126048,0.701208,0.124516,0.466237
min,0.000000,1.000000,0.000000,2.800000e+01,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,...,0.000000,0.000000,0.000000e+00,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000008,2.000000,0.000000,1.140000e+02,0.000000e+00,32.786140,1.305334e+04,0.000000e+00,0.000000,0.000000,...,0.000000,0.000000,0.000000e+00,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.001582,2.000000,2.000000,4.300000e+02,1.640000e+02,3225.806641,8.796748e+05,1.447023e+03,0.000000,0.000000,...,44.000000,0.000000,0.000000e+00,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,0.668069,12.000000,10.000000,1.418000e+03,1.102000e+03,125000.000000,8.888889e+07,2.784487e+04,3.000000,2.000000,...,89.000000,0.000000,0.000000e+00,5.000000,3.000000,0.000000,0.000000,0.000000,0.000000,1.000000
max,59.999989,9616.000000,10974.000000,1.296523e+07,1.465555e+07,1000000.000000,5.988000e+09,2.242273e+07,4803.000000,5484.000000,...,1458.000000,172.000000,6.558056e+06,51.000000,46.000000,4.000000,4.000000,30.000000,1.000000,1.000000

In [14]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
dur,175341.0,1.359389e+00,6.483313e+00,0.0,0.000008,0.001582,6.680690e-01,5.999999e+01
spkts,175341.0,2.029866e+01,1.368876e+02,1.0,2.000000,2.000000,1.200000e+01,9.616000e+03
dpkts,175341.0,1.896959e+01,1.102583e+02,0.0,0.000000,2.000000,1.000000e+01,1.097400e+04
sbytes,175341.0,8.844844e+03,1.747656e+05,28.0,114.000000,430.000000,1.418000e+03,1.296523e+07
dbytes,175341.0,1.492892e+04,1.436542e+05,0.0,0.000000,164.000000,1.102000e+03,1.465555e+07
rate,175341.0,9.540618e+04,1.654177e+05,0.0,32.786140,3225.806641,1.250000e+05,1.000000e+06
sload,175341.0,7.345403e+07,1.883701e+08,0.0,13053.338867,879674.750000,8.888889e+07,5.988000e+09
dload,175341.0,6.712055e+05,2.423637e+06,0.0,0.000000,1447.022705,2.784487e+04,2.242273e+07
sloss,175341.0,4.953000e+00,6.600506e+01,0.0,0.000000,0.000000,3.000000e+00,4.803000e+03
dloss,175341.0,6.948010e+00,5.273300e+01,0.0,0.000000,0.000000,2.000000e+00,5.484000e+03
sinpkt,175341.0,9.859768e+02,7.244196e+03,0.0,0.008000,0.279733,5.515689e+01,8.437149e+04
dinpkt,175341.0,8.821630e+01,9.857412e+02,0.0,0.000000,0.006000,5.105300e+01,5.671682e+04
sjit,175341.0,4.976255e+03,4.498317e+04,0.0,0.000000,0.000000,2.513295e+03,1.460480e+06
djit,175341.0,6.043538e+02,4.056383e+03,0.0,0.000000,0.000000,1.149906e+02,2.893883e+05
swin,175341.0,1.162573e+02,1.270010e+02,0.0,0.000000,0.000000,2.550000e+02,2.550000e+02
stcpb,175341.0,9.692504e+08,1.355264e+09,0.0,0.000000,0.000000,1.916651e+09,4.294959e+09
dtcpb,175341.0,9.688770e+08,1.354000e+09,0.0,0.000000,0.000000,1.913675e+09,4.294882e+09
dwin,175341.0,1.150136e+02,1.268865e+02,0.0,0.000000,0.000000,2.550000e+02,2.550000e+02
tcprtt,175341.0,4.139564e-02,7.934009e-02,0.0,0.000000,0.000000,6.548100e-02,2.518893e+00
synack,175341.0,2.102045e-02,4.334923e-02,0.0,0.000000,0.000000,2.326800e-02,2.100352e+00
ackdat,175341.0,2.037519e-02,4.052070e-02,0.0,0.000000,0.000000,3.890600e-02,1.520884e+00
smean,175341.0,1.367518e+02,2.046774e+02,28.0,57.000000,73.000000,1.000000e+02,1.504000e+03
dmean,175341.0,1.241734e+02,2.583171e+02,0.0,0.000000,44.000000,8.900000e+01,1.458000e+03
trans_depth,175341.0,1.059821e-01,7.769108e-01,0.0,0.000000,0.000000,0.000000e+00,1.720000e+02
response_body_len,175341.0,2.144292e+03,5.420797e+04,0.0,0.000000,0.000000,0.000000e+00,6.558056e+06
ct_src_dport_ltm,175341.0,5.383538e+00,8.047104e+00,1.0,1.000000,1.000000,5.000000e+00,5.100000e+01
ct_dst_sport_ltm,175341.0,4.206255e+00,5.783585e+00,1.0,1.000000,1.000000,3.000000e+00,4.600000e+01
is_ftp_login,175341.0,1.494802e-02,1.260480e-01,0.0,0.000000,0.000000,0.000000e+00,4.000000e+00
ct_ftp_cmd,175341.0,1.494802e-02,1.260480e-01,0.0,0.000000,0.000000,0.000000e+00,4.000000e+00
ct_flw_http_mthd,175341.0,1.330664e-01,7.012076e-01,0.0,0.000000,0.000000,0.000000e+00,3.000000e+01
is_sm_ips_ports,175341.0,1.575216e-02,1.245155e-01,0.0,0.000000,0.000000,0.000000e+00,1.000000e+00
label,175341.0,6.806223e-01,4.662369e-01,0.0,0.000000,1.000000,1.000000e+00,1.000000e+00

In [15]:
df.nunique().sort_values()

label                    2
is_sm_ips_ports          2
is_ftp_login             4
ct_ftp_cmd               4
dwin                     7
state                    9
attack_cat              10
trans_depth             11
ct_flw_http_mthd        11
service                 13
swin                    13
ct_dst_sport_ltm        32
ct_src_dport_ltm        47
proto                  133
dloss                  370
sloss                  409
dpkts                  443
spkts                  480
dmean                 1328
smean                 1357
response_body_len     2386
dbytes                6660
sbytes                7214
ackdat               37708
synack               40142
tcprtt               43319
dur                  74039
dinpkt               74177
dtcpb                75089
stcpb                75265
sinpkt               76050
djit                 76743
rate                 76794
sjit                 77390
dload                77474
sload                80885
dtype: int64

In [16]:
print(df["proto"].value_counts().head(20))

proto
tcp          79946
udp          63283
unas         12084
arp           2859
ospf          2595
sctp          1150
any            300
gre            225
swipe          201
mobile         201
pim            201
sun-nd         201
ipv6           201
rsvp           200
sep            193
ib             101
3pc            100
zero           100
aes-sp3-d      100
a/n            100
Name: count, dtype: int64

In [17]:
print(df["service"].value_counts())

service
-           94168
dns         47294
http        18724
smtp         5058
ftp-data     3995
ftp          3428
ssh          1302
pop3         1105
dhcp           94
snmp           80
ssl            56
irc            25
radius         12
Name: count, dtype: int64

In [18]:
print(df["state"].value_counts())

state
INT    82275
FIN    77825
CON    13152
REQ     1991
RST       83
ECO       12
PAR        1
URN        1
no         1
Name: count, dtype: int64

In [21]:
numeric_df = df.select_dtypes(include=['number'])
corr = numeric_df.corr()

In [22]:
corr['label'].sort_values(ascending=False)

label                1.000000
ct_dst_sport_ltm     0.357213
rate                 0.337979
ct_src_dport_ltm     0.305579
sload                0.182870
ackdat               0.097364
tcprtt               0.081584
synack               0.058299
dur                  0.036175
sbytes               0.018576
ct_flw_http_mthd     0.015800
trans_depth          0.010801
sloss               -0.000640
sjit                -0.007069
smean               -0.010798
ct_ftp_cmd          -0.011055
is_ftp_login        -0.011055
response_body_len   -0.021361
dinpkt              -0.022887
spkts               -0.052178
djit                -0.060870
dbytes              -0.076871
dloss               -0.094685
dpkts               -0.118591
sinpkt              -0.176110
is_sm_ips_ports     -0.184679
dtcpb               -0.250340
stcpb               -0.255006
dwin                -0.319626
swin                -0.333633
dmean               -0.341806
dload               -0.393739
Name: label, dtype: float64

In [23]:
df.select_dtypes(include=['category', 'object']).columns

Index(['proto', 'service', 'state', 'attack_cat'], dtype='object')

In [24]:
X = df.drop(columns=['label', 'attack_cat'])

y = df['label']

In [25]:
print(X.shape)
print(y.shape)

(175341, 34)
(175341,)

In [27]:
from google.colab import files
uploaded_test = files.upload()

Saving UNSW_NB15_testing-set.parquet to UNSW_NB15_testing-set.parquet

In [28]:
train_df = pd.read_parquet("UNSW_NB15_training-set.parquet")

test_df = pd.read_parquet("UNSW_NB15_testing-set.parquet")

In [29]:
print(train_df.shape)
print(test_df.shape)

(175341, 36)
(82332, 36)

In [30]:
print(train_df.columns.equals(test_df.columns))

True

In [31]:
X_train = train_df.drop(
    columns=['label', 'attack_cat']
)

y_train = train_df['label']

In [32]:
X_test = test_df.drop(
    columns=['label', 'attack_cat']
)

y_test = test_df['label']

In [35]:
from sklearn.preprocessing import LabelEncoder
import numpy as np

for col in ['proto', 'service', 'state']:
    le = LabelEncoder()

    # Convert columns to string type to avoid mixed types during unique value extraction
    train_col_str = X_train[col].astype(str)
    test_col_str = X_test[col].astype(str)

    # Combine unique values from both train and test sets to fit the encoder
    all_unique_values = np.unique(pd.concat([train_col_str, test_col_str], axis=0))
    le.fit(all_unique_values)

    X_train[col] = le.transform(train_col_str)
    X_test[col] = le.transform(test_col_str)

In [37]:
# FEature Scaling

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [38]:
from sklearn.linear_model import LogisticRegression

In [39]:
model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

In [40]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [41]:
y_pred = model.predict(X_test)

In [42]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

In [43]:
print("Accuracy:", accuracy_score(y_test, y_pred))

print("Precision:", precision_score(y_test, y_pred))

print("Recall:", recall_score(y_test, y_pred))

print("F1:", f1_score(y_test, y_pred))

print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

Accuracy: 0.6056818733906622
Precision: 0.5827066219291142
Recall: 0.9998897026383129
F1: 0.7363120233270251
[[ 4540 32460]
 [    5 45327]]
              precision    recall  f1-score   support

           0       1.00      0.12      0.22     37000
           1       0.58      1.00      0.74     45332

    accuracy                           0.61     82332
   macro avg       0.79      0.56      0.48     82332
weighted avg       0.77      0.61      0.50     82332

Switching to RandomForest due to high rate of False Positives (Alarms)

In [44]:
from sklearn.ensemble import RandomForestClassifier

In [45]:
rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

In [46]:
rf.fit(X_train, y_train)

RandomForestClassifier(n_jobs=-1, random_state=42)

In [47]:
y_pred_rf = rf.predict(X_test)

In [48]:
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Precision:", precision_score(y_test, y_pred_rf))
print("Recall:", recall_score(y_test, y_pred_rf))
print("F1:", f1_score(y_test, y_pred_rf))
print(confusion_matrix(y_test, y_pred_rf))

Accuracy: 0.8677549433998931
Precision: 0.8215099130045178
Recall: 0.9707270802082414
F1: 0.8899067726344314
[[27439  9561]
 [ 1327 44005]]

In [49]:
import pandas as pd

importance = pd.DataFrame({
    'feature': X.columns,
    'importance': rf.feature_importances_
})

importance.sort_values(
    by='importance',
    ascending=False
).head(15)

   feature  importance
10   dload    0.101087
23  ackdat    0.085529
8     rate    0.076218
22  synack    0.072759
21  tcprtt    0.063098
9    sload    0.061620
25   dmean    0.061340
6   sbytes    0.048046
0      dur    0.047919
13  sinpkt    0.041367
7   dbytes    0.039571
14  dinpkt    0.038084
24   smean    0.038010
15    sjit    0.030196
16    djit    0.024392